### ISSUE TITLE
Crash post-combat with modified ship destroyed

### ISSUE THREAD

**Issue by yrael-codes** [lyravega/lyr_ehm#5]
```
5599550 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: Slot id [CS_WS 001ML] not found on hull [fulgent_default_D]
java.lang.RuntimeException: Slot id [CS_WS 001ML] not found on hull [fulgent_default_D]
	at com.fs.starfarer.campaign.fleet.CampaignFleetMemberView.renderWeapons(Unknown Source)
	at com.fs.starfarer.campaign.fleet.CampaignFleetMemberView.renderSingle(Unknown Source)
	at com.fs.starfarer.campaign.fleet.CampaignFleetMemberView.render(Unknown Source)
	at com.fs.starfarer.campaign.fleet.CampaignFleetView.render(Unknown Source)
	at com.fs.starfarer.campaign.fleet.CampaignFleet.render(Unknown Source)
	at com.fs.starfarer.campaign.BaseCampaignEntity.render(Unknown Source)
	at com.fs.graphics.LayeredRenderer.render(Unknown Source)
	at com.fs.starfarer.campaign.BaseLocation.render(Unknown Source)
	at com.fs.starfarer.campaign.CampaignEngine.render(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.render(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
![image](https://github.com/lyravega/lyr_ehm/assets/16899279/e42d4011-7a7f-45c9-a9f1-e2cdef1bcb27)

---

Using medium->large converter, 2 small slot diverters.

Crash takes place post-combat if the ship in question is destroyed.

Love the mod! Much fun.

**Comment by lyravega** [comment]
Yup yup I am aware of this and have developed a fix [in my own build](https://github.com/lyravega/lyr_ehm/blob/2a46b68918cfaddce0c99f00bc3c6f83c8d62c28/changelog.txt#L4). However the fix utilizes a workaround that I do not want to implement unless there's absolutely no other way, hence the delay. Though it seems my time is up - I was going to release it soon after somebody reports a crash, and here we are! I'll release the patch in a few hours.

**Comment by lyravega** [comment]
Hiya, 0.7.3 is up and running. Fixes this issue you also encountered!
